# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baidu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baidu',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
